name: Generate ASCII Artwork

on: 
    workflow_dispatch: 

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:

            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y
            
            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON..... RAWR" >> dragon.txt

            
            - name: Upload Dragon text file
              uses: action/upload-artifact@v3
              with:
                name: my-artifact
                path: dragon.txt
    
    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:

            - name: Download Dragon text file
              uses: action/download-artifact@v3
              with:
                name: my-artifact
                path: dragon.txt

            - name: Test File Exists
              run: grep -i "dragon" dragon.txt

    
    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:

            - name: Download Dragon text file
              uses: action/download-artifact@v3
              with:
                name: my-artifact
                path: dragon.txt

            - name: Read File
              run: cat dragon.txt
            
